### ISSUE TITLE
Research Authentication & User Accounts

### ISSUE THREAD

**Issue by lucaswalter** [DataDogsMST/web-app#5]
I think the next big hurdle we need to plan and figure out is how we want to handle authentication and user accounts so we can register/login/logout/retrieve portfolio data for specific users. Setting this up for a SPA is something that is totally new to me, so I could definitely use some input from you guys.

While digging around online, I found this guide that seems to go pretty in-depth to building this kind of system with React/Redux and a .NET Core backend. 

I've looked through the backend code and it seems pretty well setup and extensible, however I don't have a clue to what is going on with the react/redux portion of things. @dnhess Would you mind looking this over and sharing your thoughts about going this route?

https://www.pointblankdevelopment.com.au/blog/135/react-redux-with-aspnet-core-20-login-registration-tutorial-example

**Comment by dnhess** [comment]
I'm not really too familiar with handling users and all the stuff that goes with it, but this seems like a pretty solid guide. I really like how the guide went into the file structure that they use and provided some insight into why they did things in a certain way. I think that it could be a good idea to do some restructuring the frontend to follow the folder structure of the linked tutorial because it provides a definite structure on where to put certain features (as long as a person reads the guide).

I also noticed in the guide that it mentions actions and reducers which is a pretty big part of redux (you can find the basics here: https://redux.js.org/basics). I know that I am going to go ahead and read over the redux basics again because I'm a little rusty on it, but it basically provides a way to access and modify states inside one global store which is super nice. 

Anyway as I said earlier I do think we should go this route and potentially follow the folder structure in the guide as it has some nice practices inside of it. It also provides a nice introduction into the react/redux world by explaining why the folder structure is how it is and what each file in the structure is doing.

**Comment by lucaswalter** [comment]
Thanks! Going to check out that into guide to redux right now. 

Another note on the backend side of things: Their way of setting up the "User" entity is very well done and allows us to easily create and associate data like their portfolio and imported trades.

**Comment by dnhess** [comment]
That is nice. Being able to setup portfolios and imported trades easily will save us a lot of time
